export const artworkManifests = [
  {
    id: "ocean-24",
    title: "Calm Ocean",
    category: "Ocean",
    difficulty: "Hard",
    basePath: "public/assets/artworks/ocean-24",
    assetVersion: "20260512-metadata-cache",
  },
  {
    id: "mountain-window-24",
    title: "Mountain Window",
    category: "Cozy Views",
    difficulty: "Medium",
    basePath: "public/assets/artworks/mountain-window-24",
    assetVersion: "20260512-metadata-cache",
  },
  {
    id: "cat-sofa-24",
    title: "Cat on Sofa",
    category: "Cozy Home",
    difficulty: "Hard",
    basePath: "public/assets/artworks/cat-sofa-24",
    assetVersion: "20260512-metadata-cache",
  },
  {
    id: "tea-garden-50",
    title: "Tea Garden Corner",
    category: "Garden",
    difficulty: "Easy",
    basePath: "public/assets/artworks/tea-garden-50",
    assetVersion: "20260512-new-themes",
  },
  {
    id: "reading-nook-100",
    title: "Reading Nook Afternoon",
    category: "Cozy Home",
    difficulty: "Medium",
    basePath: "public/assets/artworks/reading-nook-100",
    assetVersion: "20260512-new-themes",
  },
  {
    id: "lantern-canal-200",
    title: "Lantern Canal Evening",
    category: "Travel",
    difficulty: "Hard",
    basePath: "public/assets/artworks/lantern-canal-200",
    assetVersion: "20260512-new-themes",
  },
];
